# Generated by Django 5.2.11 on 2026-02-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('image', models.ImageField(upload_to='category', verbose_name='ФОто')),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категори',
                'verbose_name_plural': 'Категорий',
            },
        ),
    ]
